# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/app

    steps:
      - checkout

      - run:
          name: switch to directory of fetch-from-big-query
          command: |
            cd $HOME/app/functions/javascript/fetch-from-big-query

      - run:
          name: install node modules
          command: |
            cd $HOME/app/functions/javascript/fetch-from-big-query && npm install
            cd $HOME/app/functions/javascript/sns-to-pubsub && npm install

      - run:
          name: Run linter
          command: |
            cd $HOME/app/functions/javascript/fetch-from-big-query && npm run lint
            cd $HOME/app/functions/javascript/sns-to-pubsub && npm run lint

      - run:
          name: Run tests
          command: |
            cd $HOME/app/functions/javascript/fetch-from-big-query && npm test
            cd $HOME/app/functions/javascript/sns-to-pubsub && npm test
