FACTOR_TO_CONVERT_HUNDREDTH_CENT_TO_WHOLE_CURRENCY = 0.0001
SAVING_EVENT_TRANSACTION_TYPE = 'SAVING_EVENT'
WITHDRAWAL_TRANSACTION_TYPE = 'WITHDRAWAL'
USER_OPENED_APP_EVENT_CODE = 'USER_OPENED_APP'
EXTERNAL_EVENT_SOURCE = 'AMPLITUDE'
INTERNAL_EVENT_SOURCE = 'INTERNAL_SERVICES'
ENTERED_SAVINGS_FUNNEL_EVENT_CODE = 'INITIATED_SAVING_EVENT'
ENTERED_WITHDRAWAL_FUNNEL_EVENT_CODE = 'INITIATED_WITHDRAWAL_EVENT'